development:
  adapter: postgresql
  host: 127.0.0.1
  database: teachbase_dev
  username: postgres
  password: '10071991'

test:
  adapter: postgresql
  host: 127.0.0.1
  database: teachbase_test
  username: postgres
  password: '10071991'

# production:
#   adapter: postgresql
#   host: localhost
#   database: teachbase
#   username: teachbase
#   password: teachbase
