development:
  adapter: postgresql
  host: localhost
  database: teachbase_dev
  username: teachbase
  password: teachbase

test:
  adapter: postgresql
  host: localhost
  database: teachbase_test
  username: teachbase
  password: teachbase

production:
  adapter: postgresql
  host: localhost
  database: teachbase
  username: teachbase
  password: teachbase
